modules:
  - app
  - build-logic/plugins/git-properties
  - build-logic/plugins/jib
  - core/package
  - core/project
  - core/scm-owner
  - core/scm-repository
  - core/search
  - core/storage
  - integrations/ai
  - integrations/github
  - integrations/maven

plugins:
  - ./build-logic/plugins/git-properties
  - ./build-logic/plugins/jib
